const Courses = [
  {
    id: 1,
    title: "JavaScript",
    category: "Programming",
    level: "Beginner",
    duration: "20 hours",
  },
  {
    id: 2,
    title: "React",
    category: "Frontend",
    level: "Intermediate",
    duration: "15 hours",
  },
  {
    id: 3,
    title: "Python",
    category: "Programming",
    level: "Beginner",
    duration: "25 hours",
  },
  {
    id: 4,
    title: "Java",
    category: "Programming",
    level: "Intermediate",
    duration: "30 hours",
  },
  {
    id: 5,
    title: "HTML",
    category: "Frontend",
    level: "Beginner",
    duration: "10 hours",
  },
  {
    id: 6,
    title: "CSS",
    category: "Frontend",
    level: "Beginner",
    duration: "12 hours",
  },
  {
    id: 7,
    title: "Node.js",
    category: "Backend",
    level: "Intermediate",
    duration: "18 hours",
  },
  {
    id: 8,
    title: "Spring Boot",
    category: "Backend",
    level: "Advanced",
    duration: "25 hours",
  },
  {
    id: 9,
    title: "SQL",
    category: "Database",
    level: "Beginner",
    duration: "14 hours",
  },
  {
    id: 10,
    title: "MongoDB",
    category: "Database",
    level: "Intermediate",
    duration: "16 hours",
  },
  {
    id: 11,
    title: "Git & GitHub",
    category: "Tools",
    level: "Beginner",
    duration: "8 hours",
  },
  {
    id: 12,
    title: "TypeScript",
    category: "Frontend",
    level: "Intermediate",
    duration: "18 hours",
  },
  {
    id: 13,
    title: "Data Structures",
    category: "Computer Science",
    level: "Intermediate",
    duration: "35 hours",
  },
  {
    id: 14,
    title: "Algorithms",
    category: "Computer Science",
    level: "Advanced",
    duration: "40 hours",
  },
  {
    
    id: 15,
    title: "REST API",
    category: "Backend",
    level: "Intermediate",
    duration: "12 hours",
  },
];

export default Courses;
